# hazard-check PowerShell behavioral tests.
if (-not (Get-Command Invoke-Hook -ErrorAction SilentlyContinue)) { . (Join-Path $PSScriptRoot '_HookHarness.ps1') }
$scripts=(Resolve-Path(Join-Path $PSScriptRoot '..\..\scripts')).Path;$hazardPs=Join-Path $scripts 'hazard-check.ps1'
function Put($Path,$Text,[bool]$Bom=$false){[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($Bom))}
$hazardHeading='## Known Hazard Areas';$hazardHeader='| Area / file(s) | Hazard | Status | Reviewed |';$hazardSeparator='|---|---|---|---|';$noNotable='_No notable hazards detected — confirm with the team._'
function WriteContext($Root,$Rows=@(),[switch]$Pending,[switch]$NoSection,[switch]$Hostile){$body=if($NoSection){"# Context`nNothing here.`n"}else{"# Context`n$(if($Pending){'KNOWN_HAZARD_AREAS_PENDING'})`n## Known Hazard Areas`n| Area / file(s) | Hazard | Status | Reviewed |`n|---|---|---|---|`n$($Rows-join"`n")`n## Next`n"};if($Hostile){$body=$body-replace"`n","`r`n"};Put(Join-Path $Root 'FRAMEWORK-CONTEXT.md')$body ([bool]$Hostile)}
function WriteRawContext($Root,[string[]]$Lines,[switch]$NoFinalNewline){$body=$Lines-join"`n";if(-not$NoFinalNewline){$body+="`n"};Put(Join-Path $Root 'FRAMEWORK-CONTEXT.md')$body}
function Fixture($Rows=@(),[switch]$Pending,[switch]$NoSection,[switch]$Missing,[switch]$Hostile){$r=Join-Path([IO.Path]::GetTempPath())('hazard-'+[guid]::NewGuid());New-Item -ItemType Directory -Force $r|Out-Null;if(-not$Missing){WriteContext $r $Rows -Pending:$Pending -NoSection:$NoSection -Hostile:$Hostile};$r}
function ConsumerFixture($Rows=@()){$seed=Split-Path $scripts -Parent;if(-not(Test-Path(Join-Path $seed 'AGENTS.md'))){$repo=(Resolve-Path(Join-Path $PSScriptRoot '..\..\..\..')).Path;$seed=Join-Path $repo 'dist/dotnet'};$r=Join-Path([IO.Path]::GetTempPath())('hazard-docsync-'+[guid]::NewGuid());Copy-Item -LiteralPath $seed -Destination $r -Recurse -Force;Copy-Item -LiteralPath $hazardPs -Destination(Join-Path $r 'scripts/hazard-check.ps1') -Force;Remove-Item -LiteralPath(Join-Path $r '.template-repo') -Force -ErrorAction SilentlyContinue;$claude=Join-Path $r 'CLAUDE.md';Put $claude ([IO.File]::ReadAllText($claude).Replace('BOOTSTRAP_PENDING','BOOTSTRAP_COMPLETE'));WriteContext $r $Rows;$r}
function Row($Area,$Status='[VERIFIED]',$Reviewed='2026-01-01'){"| $Area | risk | $Status | $Reviewed |"}
function Make($Root,$Path,[switch]$Directory){$p=Join-Path $Root $Path;if($Directory){New-Item -ItemType Directory -Force $p|Out-Null}else{New-Item -ItemType Directory -Force (Split-Path $p -Parent)|Out-Null;Put $p 'x'}}
$script:leafPsRuns=0;$script:wrapperPsRuns=0
function RunLeafPs($Root){$script:leafPsRuns+=1;RunArg $hazardPs $Root}
function RunWrapperPs($Root){$script:wrapperPsRuns+=1;RunArg(Join-Path $Root 'scripts/docs-sync-check.ps1')}
function CaptureLeaf($Root){[pscustomobject]@{P=(RunLeafPs $Root)}}
function CaptureDocs($Root){[pscustomobject]@{P=(RunWrapperPs $Root)}}
function AssertLeaf($pair,$Expected,$Label,$Text=''){Assert($pair.P.Exit-eq$Expected)"$Label ps1 exit $($pair.P.Exit): $($pair.P.Out) $($pair.P.Err)";if($Text){Assert($pair.P.Out-match[regex]::Escape($Text))"$Label ps1 missing text: $Text -- $($pair.P.Out)"}}
function AssertDocs($pair,$Expected,$Label,$Text=''){$success='(?m)^All AI Tech Lead framework checks passed\.\r?$';Assert($pair.P.Exit-eq$Expected)"$Label docs ps1 exit $($pair.P.Exit): $($pair.P.Out) $($pair.P.Err)";if($Text){Assert($pair.P.Out-match[regex]::Escape($Text))"$Label docs ps1 missing text: $Text -- $($pair.P.Out)"};if($Expected-eq0){Assert($pair.P.Out-match$success)"$Label docs ps1 omitted exact final success line"}else{Assert($pair.P.Out-notmatch$success)"$Label docs ps1 printed a false final success line"}}
function Check($Root,$Expected,$Label,$Text=''){AssertLeaf (CaptureLeaf $Root) $Expected $Label $Text}
function CheckDocs($Root,$Expected,$Label,$Text=''){AssertDocs (CaptureDocs $Root) $Expected $Label $Text}
function HashOrMissing($Path){if(Test-Path -LiteralPath $Path){(Get-FileHash $Path -Algorithm SHA256).Hash}else{'<missing>'}}
function CountText($Text,$Needle){[regex]::Matches([string]$Text,[regex]::Escape($Needle)).Count}
function AssertNoFinalNewline($Path){$bytes=[IO.File]::ReadAllBytes($Path);Assert($bytes.Count-gt0)'fixture is empty';Assert($bytes[-1]-ne10-and$bytes[-1]-ne13)'fixture unexpectedly ends in CR/LF'}
Reset-Tests
It 'missing path fails and names it'{$r=Fixture @(Row 'src/Payments.cs');try{Check $r 1 'missing path' 'src/Payments.cs'}finally{Remove-Item -Recurse -Force $r}}
It 'existing path passes'{$r=Fixture @(Row 'src/Payments.cs');try{Make $r 'src/Payments.cs';Check $r 0 'existing path'}finally{Remove-Item -Recurse -Force $r}}
$noLiteral=@(@{n='pure prose';a='the payment reconciliation flow'},@{n='symbol only';a='`TenantContext`'},@{n='URL only';a='https://wiki.example.com/hazards'},@{n='glob only';a='src/app/**/*.component.ts'},@{n='bare glob only';a='*.ts'})
foreach($c in $noLiteral){It "$($c.n) cannot replace an exact path"{$r=Fixture @(Row $c.a);try{Check $r 1 $c.n 'must include at least one exact resolving repository-root-relative path'}finally{Remove-Item -Recurse -Force $r}}}
It 'existing extensionless directory passes'{$r=Fixture @(Row 'src/app');try{Make $r 'src/app' -Directory;Check $r 0 'directory'}finally{Remove-Item -Recurse -Force $r}}
It 'prose containing existing path passes'{$r=Fixture @(Row 'concurrency in `src/Payments.cs` and its callers');try{Make $r 'src/Payments.cs';Check $r 0 'prose path'}finally{Remove-Item -Recurse -Force $r}}
It 'labels symbols URLs and globs remain ancillary beside an exact path'{$r=Fixture @(Row '`src/Payments.cs` payments `TenantContext` https://wiki.example.com/hazards src/app/**/*.component.ts');try{Make $r 'src/Payments.cs';Check $r 0 'ancillary text'}finally{Remove-Item -Recurse -Force $r}}
It 'second missing candidate fails'{$r=Fixture @(Row '`src/Payments.cs`, `src/Missing.cs`');try{Make $r 'src/Payments.cs';Check $r 1 'multiple candidates' 'src/Missing.cs'}finally{Remove-Item -Recurse -Force $r}}
It 'bare filename resolves at the repository root'{$r=Fixture @(Row 'PaymentService.cs');try{Make $r 'PaymentService.cs';Check $r 0 'root bare filename'}finally{Remove-Item -Recurse -Force $r}}
It 'nested-only bare filename does not satisfy a root-level reference'{$r=Fixture @(Row 'PaymentService.cs');try{Make $r 'src/Domain/PaymentService.cs';Check $r 1 'nested-only bare filename' 'PaymentService.cs'}finally{Remove-Item -Recurse -Force $r}}
It 'bare filename that exists nowhere fails'{$r=Fixture @(Row 'PaymentService.cs');try{Make $r 'src/Domain/Other.cs';Check $r 1 'bare filename missing' 'PaymentService.cs'}finally{Remove-Item -Recurse -Force $r}}
It 'a resolving traversal outside the repository is rejected'{$r=Fixture @(Row '../hazard-outside.txt');$outside=Join-Path(Split-Path $r -Parent)'hazard-outside.txt';try{Put $outside 'x';Check $r 1 'traversal' 'not a safe repository-root-relative path'}finally{Remove-Item -Recurse -Force $r;Remove-Item -LiteralPath $outside -Force -ErrorAction SilentlyContinue}}
# A row whose cells are all empty is malformed content, not a table separator.
It 'all-empty row is reported, not treated as a separator'{$r=Fixture @('|  |  |  |  |');try{Check $r 1 'all-empty row' "unrecognised Status ''"}finally{Remove-Item -Recurse -Force $r}}
$simpleStatuses=@('[VERIFIED]','[SUSPECTED]','[UNVERIFIED]')
foreach($simpleStatus in $simpleStatuses){It "$simpleStatus is an exact accepted status"{$r=Fixture @(Row 'src/Payments.cs' $simpleStatus);try{Make $r 'src/Payments.cs';Check $r 0 $simpleStatus}finally{Remove-Item -Recurse -Force $r}}}
It 'unrecognised status fails for status reason'{$r=Fixture @(Row 'src/Payments.cs' '[PROBABLY]');try{Make $r 'src/Payments.cs';Check $r 1 'bad status' "unrecognised Status '[PROBABLY]'"}finally{Remove-Item -Recurse -Force $r}}
It 'status tokens are case-sensitive'{$r=Fixture @(Row 'src/Payments.cs' '[verified]');try{Make $r 'src/Payments.cs';Check $r 1 'lower-case status' "unrecognised Status '[verified]'"}finally{Remove-Item -Recurse -Force $r}}
It 'reviewed-not-hazard status passes'{$r=Fixture @(Row 'src/Payments.cs' '[REVIEWED: not a hazard — 2026-01-01]');try{Make $r 'src/Payments.cs';Check $r 0 'reviewed status'}finally{Remove-Item -Recurse -Force $r}}
$badReviewedStatuses=@('[REVIEWED: not a hazard','[REVIEWED: not a hazard — 2026-01-01] trailing','[REVIEWED: not a hazard — 2026-02-30]')
foreach($badReviewedStatus in $badReviewedStatuses){It "incomplete or garbage reviewed status is rejected: $badReviewedStatus"{$r=Fixture @(Row 'src/Payments.cs' $badReviewedStatus);try{Make $r 'src/Payments.cs';Check $r 1 'bad reviewed status'}finally{Remove-Item -Recurse -Force $r}}}
It 'reviewed status date agrees with Reviewed column'{$r=Fixture @(Row 'src/Payments.cs' '[REVIEWED: not a hazard — 2026-01-02]' '2026-01-01');try{Make $r 'src/Payments.cs';Check $r 1 'conflicting reviewed dates' 'does not match Reviewed'}finally{Remove-Item -Recurse -Force $r}}
It 'non-date fails for date reason'{$r=Fixture @(Row 'src/Payments.cs' '[VERIFIED]' 'not-a-date');try{Make $r 'src/Payments.cs';Check $r 1 'non-date' "invalid Reviewed date 'not-a-date'"}finally{Remove-Item -Recurse -Force $r}}
It 'non-calendar date fails for date reason'{$r=Fixture @(Row 'src/Payments.cs' '[VERIFIED]' '2026-02-30');try{Make $r 'src/Payments.cs';Check $r 1 'calendar date' "invalid Reviewed date '2026-02-30'"}finally{Remove-Item -Recurse -Force $r}}
It 'year zero is non-calendar'{$r=Fixture @(Row 'src/Payments.cs' '[VERIFIED]' '0000-01-01');try{Make $r 'src/Payments.cs';Check $r 1 'year zero' "invalid Reviewed date '0000-01-01'"}finally{Remove-Item -Recurse -Force $r}}
It 'three-cell row fails for cell reason'{$r=Fixture @('| src/Payments.cs | risk | [VERIFIED] |');try{Check $r 1 'cell count' 'does not have 4 cells'}finally{Remove-Item -Recurse -Force $r}}
It 'placeholder row fails as incomplete after pending is removed'{$r=Fixture @('| _(drafted by /bootstrap)_ | _ | _ | _ |');try{Check $r 1 'placeholder' 'placeholder row'}finally{Remove-Item -Recurse -Force $r}}
It 'missing context fails as incomplete input'{$r=Fixture -Missing;try{Check $r 1 'missing context' 'FRAMEWORK-CONTEXT.md is missing'}finally{Remove-Item -Recurse -Force $r}}
It 'pending table fails as incomplete'{$r=Fixture -Pending;try{Check $r 1 'pending' 'still pending'}finally{Remove-Item -Recurse -Force $r}}
It 'missing section fails as incomplete'{$r=Fixture -NoSection;try{Check $r 1 'missing section' 'exactly one'}finally{Remove-Item -Recurse -Force $r}}
It 'BOM and CRLF table passes'{$r=Fixture @(Row 'src/Payments.cs') -Hostile;try{Make $r 'src/Payments.cs';Check $r 0 'hostile formatting'}finally{Remove-Item -Recurse -Force $r}}
It 'failing run is read-only'{$r=Fixture @(Row 'src/Missing.cs');try{$file=Join-Path $r 'FRAMEWORK-CONTEXT.md';$before=HashOrMissing $file;$result=RunLeafPs $r;$after=HashOrMissing $file;Assert($result.Exit-eq1)'ps1 did not fail';Assert($after-eq$before)'ps1 changed input'}finally{Remove-Item -Recurse -Force $r}}
It 'two bad rows count both isolated failures'{$r=Fixture @((Row 'src/Payments.cs' '[PROBABLY]'),(Row 'src/Other.cs' '[VERIFIED]' 'not-a-date'));try{Make $r 'src/Payments.cs';Make $r 'src/Other.cs';Check $r 1 'failure count' '2 hazard-check failure(s).'}finally{Remove-Item -Recurse -Force $r}}
It 'docs-sync delegates malformed hazards and preserves exact completion semantics'{$r=ConsumerFixture @(Row 'pure prose');try{CheckDocs $r 1 'docs malformed hazard' 'hazard map checks failed';WriteContext $r @(Row 'README.md');CheckDocs $r 0 'docs valid hazard'}finally{Remove-Item -Recurse -Force $r}}
It 'backticked wildcard cannot hide a later missing literal'{$r=Fixture @(Row '`src/*.cs` `src/Missing.cs` src/Existing.cs');try{Make $r 'src/Existing.cs';Check $r 1 'backtick extraction' 'src/Missing.cs'}finally{Remove-Item -Recurse -Force $r}}
It 'balanced bracket glob is ancillary even when its literal spelling exists'{$r=Fixture @(Row 'src/file[0].cs');try{Make $r 'src/file[0].cs';Check $r 1 'bracket glob' 'must include at least one exact resolving repository-root-relative path'}finally{Remove-Item -Recurse -Force $r}}
It 'unmatched bracket remains a literal path'{$r=Fixture @(Row 'src/file[0.cs');try{Make $r 'src/file[0.cs';Check $r 0 'unmatched bracket'}finally{Remove-Item -Recurse -Force $r}}
It 'balanced bracket glob remains ancillary beside a valid literal'{$r=Fixture @(Row 'src/file[0].cs src/Payments.cs');try{Make $r 'src/Payments.cs';Check $r 0 'bracket glob plus literal'}finally{Remove-Item -Recurse -Force $r}}
It 'unterminated final missing row is rejected'{$r=Fixture -Missing;try{WriteRawContext $r @('# Context',$hazardHeading,$hazardHeader,$hazardSeparator,(Row 'src/Missing.cs')) -NoFinalNewline;$file=Join-Path $r 'FRAMEWORK-CONTEXT.md';AssertNoFinalNewline $file;Check $r 1 'unterminated missing row' 'src/Missing.cs'}finally{Remove-Item -Recurse -Force $r}}
It 'unterminated final valid row passes'{$r=Fixture -Missing;try{WriteRawContext $r @('# Context',$hazardHeading,$hazardHeader,$hazardSeparator,(Row 'src/Payments.cs')) -NoFinalNewline;Make $r 'src/Payments.cs';$file=Join-Path $r 'FRAMEWORK-CONTEXT.md';AssertNoFinalNewline $file;Check $r 0 'unterminated valid row'}finally{Remove-Item -Recurse -Force $r}}
It 'unterminated final pending marker fails as incomplete'{$r=Fixture -Missing;try{WriteRawContext $r @('# Context',$hazardHeading,$hazardHeader,$hazardSeparator,$noNotable,'KNOWN_HAZARD_AREAS_PENDING') -NoFinalNewline;$file=Join-Path $r 'FRAMEWORK-CONTEXT.md';AssertNoFinalNewline $file;Check $r 1 'unterminated pending marker' 'still pending'}finally{Remove-Item -Recurse -Force $r}}
It 'placeholder Area with non-placeholder cells is ordinary invalid content'{$r=Fixture @('| _(drafted by /bootstrap)_ | risk | [VERIFIED] | 2026-01-01 |');try{Check $r 1 'placeholder Area only' 'not a safe repository-root-relative path'}finally{Remove-Item -Recurse -Force $r}}
It 'case-variant placeholder is not the exact sentinel'{$r=Fixture @('| _(Drafted by /bootstrap)_ | _ | _ | _ |');try{Check $r 1 'case-variant placeholder' "unrecognised Status '_'"}finally{Remove-Item -Recurse -Force $r}}
It 'placeholder values with extra framing are not the exact sentinel'{$r=Fixture @('| _(drafted by /bootstrap)_ | _ | _ | _ | extra |');try{Check $r 1 'placeholder framing' 'does not have 4 cells'}finally{Remove-Item -Recurse -Force $r}}
It 'leading dot segment is unsafe rather than normalized away'{$r=Fixture @(Row './README.md');try{Make $r 'README.md';Check $r 1 'leading dot segment' 'not a safe repository-root-relative path'}finally{Remove-Item -Recurse -Force $r}}
It 'rooted drive path is unsafe'{$r=Fixture @(Row 'C:/README.md');try{Check $r 1 'rooted drive' 'not a safe repository-root-relative path'}finally{Remove-Item -Recurse -Force $r}}
It 'drive-relative path is classified unsafe before path shape'{$r=Fixture @(Row 'C:README.md');try{Check $r 1 'drive-relative path' 'not a safe repository-root-relative path'}finally{Remove-Item -Recurse -Force $r}}
It 'duplicate exact hazard headings are rejected'{$r=Fixture -Missing;try{WriteRawContext $r @('# Context',$hazardHeading,$hazardHeader,$hazardSeparator,(Row 'src/Payments.cs'),'## Other','text',$hazardHeading,$hazardHeader,$hazardSeparator,(Row 'src/Payments.cs'),'## Next');Make $r 'src/Payments.cs';Check $r 1 'duplicate headings' 'exactly one'}finally{Remove-Item -Recurse -Force $r}}
It 'case-variant hazard heading is not an exact section'{$r=Fixture -Missing;try{WriteRawContext $r @('# Context','## known Hazard Areas',$hazardHeader,$hazardSeparator,(Row 'src/Payments.cs'),'## Next');Make $r 'src/Payments.cs';Check $r 1 'case-variant heading' 'exactly one'}finally{Remove-Item -Recurse -Force $r}}
It 'exact heading accepts trailing horizontal whitespace'{$r=Fixture -Missing;try{WriteRawContext $r @('# Context',($hazardHeading+"`t  "),$hazardHeader,$hazardSeparator,(Row 'src/Payments.cs'),'## Next');Make $r 'src/Payments.cs';Check $r 0 'heading horizontal whitespace'}finally{Remove-Item -Recurse -Force $r}}
It 'exact no-notable outcome passes beside a case-variant pending decoy'{$r=Fixture -Missing;try{WriteRawContext $r @('# Context','Known_Hazard_Areas_Pending',$hazardHeading,$hazardHeader,$hazardSeparator,$noNotable,'## Next');Check $r 0 'no-notable outcome' 'hazard-check passed.'}finally{Remove-Item -Recurse -Force $r}}
It 'docs-sync rejects the backtick extraction bypass without final success'{$r=ConsumerFixture @(Row '`src/*.cs` `src/Missing.cs` README.md');try{CheckDocs $r 1 'docs backtick bypass' 'hazard map checks failed'}finally{Remove-Item -Recurse -Force $r}}
It 'docs-sync rejects the bracket glob bypass without final success'{$r=ConsumerFixture @(Row 'src/file[0].cs');try{Make $r 'src/file[0].cs';CheckDocs $r 1 'docs bracket bypass' 'hazard map checks failed'}finally{Remove-Item -Recurse -Force $r}}
It 'framed exact dot segments remain unsafe without becoming missing paths'{$area='`.` `src/.` `src/..` `src/..:` `src/...` `(src/..);` `''(src/..);''` `(src/..).` `(src/..):` `''(src/..);''.` `''(src/..);'':` `"(src/..),;;"` `README.md`';$r=ConsumerFixture @(Row $area);try{$controls=@('src','src/..)','src/..)''','src/..);''','(src/..)','''(src/..);''');foreach($control in $controls){$null=[IO.Directory]::CreateDirectory((Join-Path $r $control))};Make $r 'README.md';$leaf=CaptureLeaf $r;$docs=CaptureDocs $r;foreach($control in $controls){Assert([IO.Directory]::Exists((Join-Path $r $control)))"dot segment control was not created: $control"};$unsafe='hazard row names a path that is not a safe repository-root-relative path:';AssertLeaf $leaf 1 'dot segment safety' '12 hazard-check failure(s).';AssertDocs $docs 1 'docs dot segment safety' 'hazard map checks failed';foreach($capture in @(@{n='leaf ps1';o=$leaf.P.Out},@{n='docs ps1';o=$docs.P.Out})){Assert((CountText $capture.o $unsafe)-eq12)"$($capture.n) did not report exactly 12 unsafe paths: $($capture.o)";Assert($capture.o-notmatch'does not exist')"$($capture.n) misclassified an unsafe path as missing: $($capture.o)"};Assert($leaf.P.Out-notmatch'(?m)^hazard-check passed\.\r?$')'dot segment ps1 leaf printed false success'}finally{Remove-Item -Recurse -Force $r}}
It 'bare drive prefix remains unsafe beside a valid literal'{$r=Fixture @(Row '`C:` `README.md`');try{Make $r 'README.md';Check $r 1 'bare drive prefix' 'not a safe repository-root-relative path'}finally{Remove-Item -Recurse -Force $r}}
It 'header and separator alone are not a completed outcome'{$r=Fixture @();try{Check $r 1 'header-only section' 'at least one hazard row or the exact no-notable outcome'}finally{Remove-Item -Recurse -Force $r}}
It 'arbitrary non-table prose is not a completed outcome'{$r=Fixture -Missing;try{WriteRawContext $r @('# Context',$hazardHeading,'_Something else._','## Next');Check $r 1 'arbitrary outcome' 'at least one hazard row or the exact no-notable outcome'}finally{Remove-Item -Recurse -Force $r}}
It 'no-notable outcome cannot be mixed with a real row'{$r=Fixture @($noNotable,(Row 'README.md'));try{Make $r 'README.md';Check $r 1 'mixed outcome' 'cannot contain both'}finally{Remove-Item -Recurse -Force $r}}
It 'framed dot-named and unmatched-wrapper paths remain literal'{$spellings=@('`(src/.cache/config.json);`','`''(src/.cache/config.json);''`','`(src/.cache/config.json).`','`(src/.cache/config.json):`','`''(src/.cache/config.json);''.`','`''(src/.cache/config.json);'':`','`"(src/.cache/config.json),;;"`','`src/.cache/(unmatched-leading.json`','`src/.cache/unmatched.json)`','`src/.cache/unmatched-single.json''`');$rows=@();foreach($spelling in $spellings){$rows+=Row $spelling};$r=ConsumerFixture $rows;try{$cache=[IO.Directory]::CreateDirectory((Join-Path $r 'src/.cache')).FullName;foreach($name in @('config.json','(unmatched-leading.json','unmatched.json)','unmatched-single.json''')){Put(Join-Path $cache $name)'x'};$leaf=CaptureLeaf $r;$docs=CaptureDocs $r;foreach($absent in @('unmatched-leading.json','unmatched.json','unmatched-single.json')){Assert(-not[IO.File]::Exists((Join-Path $cache $absent)))"unmatched-wrapper stripped control unexpectedly exists: $absent"};AssertLeaf $leaf 0 'framed dot-named paths' 'hazard-check passed.';AssertDocs $docs 0 'docs framed dot-named paths' 'hazard-check passed.'}finally{Remove-Item -Recurse -Force $r}}
It 'ordinary path accepts one sentence-final dot and colon'{$r=Fixture @(Row '`src/Payments.cs.` `src/Payments.cs:`');try{Make $r 'src/Payments.cs';Check $r 0 'sentence punctuation'}finally{Remove-Item -Recurse -Force $r}}
It 'case-variant no-notable text is not the exact outcome'{$r=Fixture @('_No Notable hazards detected — confirm with the team._');try{Check $r 1 'case-variant no-notable' 'at least one hazard row or the exact no-notable outcome'}finally{Remove-Item -Recurse -Force $r}}
It 'no-notable text with trailing garbage is not the exact outcome'{$r=Fixture @("$noNotable trailing");try{Check $r 1 'garbage no-notable' 'at least one hazard row or the exact no-notable outcome'}finally{Remove-Item -Recurse -Force $r}}
It 'docs-sync captures every incomplete lifecycle state before asserting'{$r=ConsumerFixture @(Row 'README.md');try{$captures=[Collections.Generic.List[object]]::new();$context=Join-Path $r 'FRAMEWORK-CONTEXT.md';Remove-Item -LiteralPath $context -Force;$captures.Add([pscustomobject]@{Label='docs missing context';Expected=1;Text='FRAMEWORK-CONTEXT.md is missing';Pair=(CaptureDocs $r)});WriteContext $r @() -Pending;$captures.Add([pscustomobject]@{Label='docs pending';Expected=1;Text='still pending';Pair=(CaptureDocs $r)});WriteContext $r @() -NoSection;$captures.Add([pscustomobject]@{Label='docs absent section';Expected=1;Text='exactly one';Pair=(CaptureDocs $r)});WriteContext $r @('| _(drafted by /bootstrap)_ | _ | _ | _ |');$captures.Add([pscustomobject]@{Label='docs placeholder';Expected=1;Text='placeholder row';Pair=(CaptureDocs $r)});WriteContext $r @();$captures.Add([pscustomobject]@{Label='docs header only';Expected=1;Text='at least one hazard row or the exact no-notable outcome';Pair=(CaptureDocs $r)});WriteRawContext $r @('# Context',$hazardHeading,'_Something else._','## Next');$captures.Add([pscustomobject]@{Label='docs arbitrary prose';Expected=1;Text='at least one hazard row or the exact no-notable outcome';Pair=(CaptureDocs $r)});WriteContext $r @($noNotable,(Row 'README.md'));$captures.Add([pscustomobject]@{Label='docs mixed outcome';Expected=1;Text='cannot contain both';Pair=(CaptureDocs $r)});WriteContext $r @($noNotable);$captures.Add([pscustomobject]@{Label='docs no-notable';Expected=0;Text='hazard-check passed.';Pair=(CaptureDocs $r)});foreach($capture in $captures){AssertDocs $capture.Pair $capture.Expected $capture.Label $capture.Text}}finally{Remove-Item -Recurse -Force $r}}
Write-Output "[coverage] HazardCheck subjects: ps1 leaf=$script:leafPsRuns wrapper=$script:wrapperPsRuns"
$coverageOK=$script:leafPsRuns-eq63-and$script:wrapperPsRuns-eq14
$summaryExit=Write-TestSummary 'HazardCheck.Tests';if(-not$coverageOK){Write-Output '[FAIL] HazardCheck subject count drifted; expected 63 leaf + 14 wrapper runs.';exit 1};exit $summaryExit
