if (-not (Get-Command Invoke-Hook -ErrorAction SilentlyContinue)) { . (Join-Path $PSScriptRoot '_HookHarness.ps1') }
$hooks=(Resolve-Path (Join-Path $PSScriptRoot '..\..\.claude\hooks')).Path;$ps=Join-Path $hooks 'session-start.ps1';$sh=Join-Path $hooks 'session-start.sh';$bash=Get-BashPath
function RunAt($hook,$root,$json){Push-Location $root;try{Invoke-Hook $hook $json}finally{Pop-Location}}
function Root($count){$r=Join-Path([IO.Path]::GetTempPath())('session-wiki-'+[guid]::NewGuid());New-Item -ItemType Directory -Force (Join-Path $r 'docs/wiki')|Out-Null;if($count-ge0){$x=1..$count|ForEach-Object{"- [gotcha] [entry-$_](./entry-$_.md) — fact $_"};[IO.File]::WriteAllText((Join-Path $r 'docs/wiki/INDEX.md'),("# Team Wiki Index`n"+($x-join"`n")),[Text.UTF8Encoding]::new($false))};$r}
$claude='{"hook_event_name":"SessionStart"}';$copilot='{"timestamp":1}';Reset-Tests
foreach($h in @($ps)+$(if($bash){@($sh)}else{@()})){It "small index inlined: $(Split-Path $h -Leaf)" {$r=Root 2;try{$o=RunAt $h $r $claude;Assert($o.Out-match'entry-2')'small index absent'}finally{Remove-Item -Recurse -Force $r}};It "large index summarized: $(Split-Path $h -Leaf)" {$r=Root 31;try{$o=RunAt $h $r $claude;Assert($o.Out-match'31 wiki entries — read docs/wiki/INDEX.md')'summary absent';Assert($o.Out-notmatch'entry-31')'large index leaked'}finally{Remove-Item -Recurse -Force $r}};It "missing index silent: $(Split-Path $h -Leaf)" {$r=Root -1;try{$o=RunAt $h $r $claude;Assert($o.Out-notmatch'wiki')'wiki output present'}finally{Remove-Item -Recurse -Force $r}}}
It 'Copilot JSON contains wiki in both additionalContext shapes' {$r=Root 2;try{$o=RunAt $ps $r $copilot|Select-Object -ExpandProperty Out|ConvertFrom-Json;Assert($o.additionalContext-match'entry-2')'top-level missing';Assert($o.hookSpecificOutput.additionalContext-match'entry-2')'wrapped missing'}finally{Remove-Item -Recurse -Force $r}}
It 'Copilot JSON contains large summary in both additionalContext shapes' {$r=Root 31;try{$o=RunAt $ps $r $copilot|Select-Object -ExpandProperty Out|ConvertFrom-Json;Assert($o.additionalContext-match'31 wiki entries')'top-level missing';Assert($o.hookSpecificOutput.additionalContext-match'31 wiki entries')'wrapped missing'}finally{Remove-Item -Recurse -Force $r}}
if(-not$bash){Skip 'session-start.sh wiki cases' 'no bash found'};exit(Write-TestSummary 'SessionStartWiki.Tests')
